### ISSUE TITLE
Комментарии к коммитам

### ISSUE THREAD

**Issue by andrey-ilyin** [Trindream/Front-end#1]
Комментарии к коммитам должны быть информативными. Должно быть сразу понятно, какие изменения были внесены. 

Коммиты надо группировать логически. Связанные вещи можно объединять в один коммит. Для изменений в разных частях проекта (не связанные изменения) лучше сделать несколько коммитов.

**Comment by Trindream** [comment]
Принял ко вниманию.

**Comment by andrey-ilyin** [comment]
Принято.
