### ISSUE TITLE
Ошибка в print_query_string.php

### ISSUE THREAD

**Issue by andrey-ilyin** [Trindream/Front-end#3]
Довольно банальная ошибка 
`
header("Content-Type: text/plaine");
`

Это говорит о том, что скрипты не проверялись. Надо все перепроверить. 
Для вывода сообщений об ошибках на рабочей машине можно использовать
`
ini_set('display_errors', 1);
error_reporting(E_ALL);
`

**Comment by Trindream** [comment]
Исправил все подобные ошибки.

**Comment by andrey-ilyin** [comment]
Принято.
