### ISSUE TITLE
Замечания к CheckIdentifier

### ISSUE THREAD

**Issue by andrey-ilyin** [Trindream/Front-end#6]
1. Название файла должно быть в стиле under_score.
2. Функция checkChar ни к чему. В PHP уже есть функция для проверки, содержит ли строка лишь буквы. 
3. В случае использования кодов символов надо либо вводить константы, либо писать комментарии, где какой код что означает. 
4. Идентификатор не может начинаться с подчеркивания. См. курс Информатика и програмирование - синтаксическое правило SR3. 
5. Слева и справа от оператора конкатенации должны быть пробелы. 
6. Исходный код в CheckIdentifier достаточно сложный, надо структурировать. Попробуйте разбить на функции.

**Comment by Trindream** [comment]
Постарался исправить все замечания.

**Comment by andrey-ilyin** [comment]
Стало лучше.

Сейчас функция function checkIdentifier($arrOfChar) решает несколько задач
1) Анализирует строку идентификатора - логика
2) Готовит сообщение об ошибке - элемент отображения
Обычно эти задачи рекомендуют разделять. 
Функция checkIdentifier может вернуть код ошибки, а функция showResult преобразует этот код в текстовое сообщение.

**Comment by Trindream** [comment]
Загрузил новую версию, с использованием  кода ошибки.

**Comment by andrey-ilyin** [comment]
Есть сомнения, что это верно
`$error += $ERR1;`

**Comment by Trindream** [comment]
Да, действительно, простите, не тот файл похоже загрузил. Я подправил область видимости.

**Comment by andrey-ilyin** [comment]
Вообще, прибавлять коды ошибок друг к другу странно. 
Имеет смысл так делать, если используете битовые маски. 

Вместо глобальных переменных используйте константы. 
Название для констант надо придумать, которое отражает суть.

**Comment by Trindream** [comment]
Исправил.

**Comment by andrey-ilyin** [comment]
Принято.
