### ISSUE TITLE
Добавить .sql файлы

### ISSUE THREAD

**Issue by andrey-ilyin** [Trindream/Front-end#7]
В 5 лабораторной работе надо подготовить .sql файлы, которые содержать SQL запрос для создания базы, таблиц, заполнения таблиц информацией и SQL запросы с выборкой для непосредственного решения поставленных задач. 

SQL запросы надо сгруппировать по смыслу, и не записывать все в один файл.

**Comment by Trindream** [comment]
Исправил, распределил все по отдельным файлам.

**Comment by andrey-ilyin** [comment]
Принято.
